In [2]:
#Realizamos un data head
import pandas as pd
import numpy as np

df = pd.read_csv('pax_data_1249_agreements_18-04-20.csv')
df.head()

,Con,Contp,PP,PPName,Reg,AgtId,Agt,Dat,Status,Lgt,...,TjRep,TjRSym,TjRMa,TjNR,ImUN,ImOth,ImRef,ImPK,ImE,ImSrc
0,Afghanistan,Government/territory,2,Afghanistan: 2000s Post-intervention process,Europe and Eurasia,2232,Resolution of Intra Afghan Peace Conference in...,2019-07-08,Multiparty signed/agreed,2,...,0,0,0,0,0,0,0,0,0,1
1,Afghanistan,Government,2,Afghanistan: 2000s Post-intervention process,Europe and Eurasia,1739,Agreement between the Islamic Republic of Afgh...,2016-09-22,Multiparty signed/agreed,4,...,0,0,0,0,0,0,0,0,1,1
2,Afghanistan,Government,2,Afghanistan: 2000s Post-intervention process,Europe and Eurasia,1923,Agreement between the two campaign teams regar...,2014-09-21,Multiparty signed/agreed,4,...,0,0,0,0,1,1,0,0,0,1
3,Afghanistan,Government,2,Afghanistan: 2000s Post-intervention process,Europe and Eurasia,864,Tokyo Declaration Partnership for Self-Relianc...,2012-07-08,Multiparty signed/agreed,14,...,0,0,0,1,0,0,0,0,1,1
4,Afghanistan,Government,2,Afghanistan: 2000s Post-intervention process,Europe and Eurasia,848,Conclusions of the Conference on Afghanistan a...,2011-12-05,Multiparty signed/agreed,7,...,0,0,0,1,1,0,0,0,0,1

In [3]:
#Mostramos cuales son las variables categóricas
df["Year"]=[df["Dat"][i][0:4] for i in range(len(df["Dat"]))]
cat =['Con','Reg', 'Year','Loc1ISO','Loc2ISO', 'Stage']
num =[ 'GCh', 'GRa', 'GRe', 'HrDem','EqGen', 'DevHum']

total=cat + num
total

['Con',
 'Reg',
 'Year',
 'Loc1ISO',
 'Loc2ISO',
 'Stage',
 'GCh',
 'GRa',
 'GRe',
 'HrDem',
 'EqGen',
 'DevHum']

In [4]:
from sklearn.preprocessing import MinMaxScaler

data_trans=df[total]
data_trans.head(10)

norm_n=[ 'GCh_n', 'GRa_n', 'GRe_n', 'HrDem_n','EqGen_n', 'DevHum_n']
x = data_trans[num]
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)
data_trans[norm_n] = pd.DataFrame(x_scaled)

data_trans.shape

C:\Users\TEMP.DESKTOP-N2LHM3K.000.001.002\anaconda3\lib\site-packages\pandas\core\frame.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

(1249, 18)

In [5]:
data_trans

,Con,Reg,Year,Loc1ISO,Loc2ISO,Stage,GCh,GRa,GRe,HrDem,EqGen,DevHum,GCh_n,GRa_n,GRe_n,HrDem_n,EqGen_n,DevHum_n
0,Afghanistan,Europe and Eurasia,2019,AFG,NaN,Pre,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,Afghanistan,Europe and Eurasia,2016,AFG,NaN,SubPar,0,1,0,0,1,0,0.000000,0.333333,0.000000,0.000000,0.333333,0.0
2,Afghanistan,Europe and Eurasia,2014,AFG,NaN,Imp,2,0,0,0,0,0,0.666667,0.000000,0.000000,0.000000,0.000000,0.0
3,Afghanistan,Europe and Eurasia,2012,AFG,NaN,Imp,1,0,0,2,1,0,0.333333,0.000000,0.000000,0.666667,0.333333,0.0
4,Afghanistan,Europe and Eurasia,2011,AFG,NaN,Pre,1,0,0,2,1,0,0.333333,0.000000,0.000000,0.666667,0.333333,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,Yemen,Middle East and North Africa,2008,YEM,NaN,Cea,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1245,Yemen,Middle East and North Africa,1994,YEM,NaN,Cea,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1246,Zimbabwe,Africa (excl MENA),2013,ZWE,NaN,SubComp,3,3,3,3,3,0,1.000000,1.000000,1.000000,1.000000,1.000000,0.0
1247,Zimbabwe,Africa (excl MENA),2008,ZWE,NaN,SubPar,3,2,2,3,3,0,1.000000,0.666667,0.666667,1.000000,1.000000,0.0
1248,Zimbabwe,Africa (excl MENA),2008,ZWE,NaN,Pre,0,2,0,0,1,0,0.000000,0.666667,0.000000,0.000000,0.333333,0.0

In [6]:
data_trans['Con']=[data_trans["Con"][i].replace('(','').replace(')','') for i in range(len(data_trans["Con"]))]

C:\Users\TEMP.DESKTOP-N2LHM3K.000.001.002\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [7]:
import re
con=pd.read_excel('Country.xlsx')
con.head()

a=[]
b=[]
c=[]
d=[]

def todos_elementos_iguales(lista):
    longitud = len(lista)
    for i in range(longitud-1):
        if lista[i] != lista[i+1]:
                return False
    return True



for j in range(len(con["country"])):
    v=[re.search(con["country"][j], data_trans["Con"][i]) for i in range(len(data_trans["Con"]))]
    if todos_elementos_iguales(v)==False:
        for k in range(len(v)):
            if v[k]!=None: 
                a.append(con["country"][j]) 
                b.append(con["code"][j]) 
                c.append(data_trans["Con"][k])                                                         
                d.append(data_trans["Year"][k])
                

peace_con= {"Country": a , 
                  "ISO code": b , 
                  "Con_AGR": c, 
                  "Year": d,
                  }

peacetotal =pd.DataFrame(peace_con)
peacetotal

,Country,ISO code,Con_AGR,Year
0,Afghanistan,AFG,Afghanistan,2019
1,Afghanistan,AFG,Afghanistan,2016
2,Afghanistan,AFG,Afghanistan,2014
3,Afghanistan,AFG,Afghanistan,2012
4,Afghanistan,AFG,Afghanistan,2011
...,...,...,...,...
1520,Zambia,ZMB,Angola/Burundi/Central African Republic/Democr...,2013
1521,Zambia,ZMB,Angola/Central African Republic/Democratic Rep...,2006
1522,Zimbabwe,ZWE,Zimbabwe,2013
1523,Zimbabwe,ZWE,Zimbabwe,2008
1524,Zimbabwe,ZWE,Zimbabwe,2008

In [8]:
print(peacetotal)

          Country ISO code                                            Con_AGR  \
0     Afghanistan      AFG                                        Afghanistan
1     Afghanistan      AFG                                        Afghanistan
2     Afghanistan      AFG                                        Afghanistan
3     Afghanistan      AFG                                        Afghanistan
4     Afghanistan      AFG                                        Afghanistan
...           ...      ...                                                ...
1520       Zambia      ZMB  Angola/Burundi/Central African Republic/Democr...
1521       Zambia      ZMB  Angola/Central African Republic/Democratic Rep...
1522     Zimbabwe      ZWE                                           Zimbabwe
1523     Zimbabwe      ZWE                                           Zimbabwe
1524     Zimbabwe      ZWE                                           Zimbabwe

      Year
0     2019
1     2016
2     2014
3     2012
4     2011
...    ...
1520  2013
1521  2006
1522  2013
1523  2008
1524  2008

[1525 rows x 4 columns]

In [10]:
peacetotal=peacetotal.drop(peacetotal[peacetotal['Con_AGR']=='Pakistan/Taliban'].index)
data_trans.to_excel('datatransform.xlsx')
peacetotal.to_excel('peace.xlsx')